language: ruby

addons:
  postgresql: 9.5

rvm:
  - 2.4.1
  - 2.3.3

services:
  - redis-server

sudo: required
dist: trusty
cache: yarn

before_install:
  - git clone --depth=1 https://github.com/discourse/discourse.git build; cd build;
  - gem install bundler rubocop
  - git clone --depth=1 -b $TRAVIS_BRANCH https://github.com/$TRAVIS_REPO_SLUG.git plugins/discourse-prometheus-alert-receiver
  - yarn global add eslint babel-eslint
  - eslint --ext .es6 plugins/**/assets/javascripts
  - cd plugins/discourse-prometheus-alert-receiver; rubocop

before_script:
  - bundle exec rake db:create db:migrate

install:
  - bundle install --without development --deployment --retry=3 --jobs=3

script:
  - LOAD_PLUGINS=1 bundle exec rake plugin:spec['discourse-prometheus-alert-receiver']
