language: ruby

addons:
  postgresql: 9.6

rvm:
  - 2.5.0

services:
  - redis-server

sudo: required
dist: trusty
cache: yarn

before_install:
  - git clone --depth=1 https://github.com/discourse/discourse.git build; cd build;
  - git clone --depth=1 -b $TRAVIS_BRANCH https://github.com/$TRAVIS_REPO_SLUG.git plugins/discourse-prometheus-alert-receiver
  - git clone --depth=1 https://github.com/discourse/discourse-assign.git plugins/discourse-assign

before_script:
  - bundle exec rake db:create db:migrate

install:
  - bundle install --without development --deployment --retry=3 --jobs=3

script:
  - LOAD_PLUGINS=1 bundle exec rake plugin:spec['discourse-prometheus-alert-receiver']
